from django.conf.urls import url

from . import views
from .models import ability, equipment, items

urlpatterns = [
    url(r'^parties/$', views.browser.parties, name='sheet-views-parties'),
    url(r'^classes/$', views.browser.all_classes, name='sheet-views-classes'),
    url(r'^combos/$', views.browser.all_combos, name='sheet-views-all-combos'),
    url(r'^heads/$', views.browser.all_equipment, {'wearables': items.heads.values()},
        name='sheet-views-heads'),
    url(r'^necks/$', views.browser.all_equipment, {'wearables': items.necks.values()},
        name='sheet-views-necks'),
    url(r'^chests/$', views.browser.all_equipment, {'wearables': items.chests.values()},
        name='sheet-views-chests'),
    url(r'^shields/$', views.browser.all_equipment, {'wearables': items.shields.values()},
        name='sheet-views-shields'),
    url(r'^hands/$', views.browser.all_equipment, {'wearables': items.hands.values()},
        name='sheet-views-hands'),
    url(r'^feets/$', views.browser.all_equipment, {'wearables': items.feets.values()},
        name='sheet-views-feets'),
    url(r'^utilities/$', views.browser.all_equipment, {'wearables': items.utilities.values()},
        name='sheet-views-utilities'),
    url(r'^weapons/$', views.browser.all_weapons, {'weapons': items.weapons.values()},
        name='sheet-views-weapons'),
    url(r'^items/$', views.browser.all_items, {'item_set': items.items.values()},
        name='sheet-views-items'),
    url(r'^shape_pictures/$', views.browser.pictures, {'picture_enum': equipment.Shape},
        name='sheet-views-shape-pictures'),
    url(r'^weapon_pictures/$', views.browser.pictures, {'picture_enum': equipment.WeaponPicture},
        name='sheet-views-weapon-pictures'),
    url(r'^ability_pictures/$', views.browser.pictures, {'picture_enum': ability.AbilityPicture},
        name='sheet-views-ability-pictures'),
    url(r'^(?P<character_id>[0-9]+)/stats/$', views.character.stats, name='sheet-views-stats'),
    url(r'^(?P<character_id>[0-9]+)/class/$', views.character.cls, name='sheet-views-class'),
    url(r'^(?P<character_id>[0-9]+)/abilities/$', views.character.unlock_abilities,
        name='sheet-views-abilities'),
    url(r'^(?P<character_id>[0-9]+)/combos/$', views.character.combos, name='sheet-views-combos'),
    url(r'^(?P<character_id>[0-9]+)/equip/$', views.character.equip, name='sheet-views-equip'),
    url(r'^(?P<character_id>[0-9]+)/level_up/$', views.character.level_up,
        name='sheet-views-level-up'),
    url(r'^(?P<character_id>[0-9]+)/skill_points/$', views.character.skill_points,
        name='sheet-views-skill-points'),
    url(r'^(?P<character_id>[0-9]+)/party/$', views.character.party, name='sheet-views-party'),
    url(r'^(?P<character_id>[0-9]+)/roll20/$', views.character.roll20, name='sheet-views-roll20'),
]
